# Generated by Django 2.2.1 on 2019-06-03 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pubapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=300)),
                ('birth_year', models.DateField()),
                ('expiration_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StaticImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=pubapp.models.get_constant_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubapp.Character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioType', models.CharField(max_length=32)),
                ('bioText', models.CharField(max_length=512)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubapp.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='chosen_user',
            field=models.ManyToManyField(through='pubapp.CharacterUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pubapp.StaticImage'),
        ),
    ]
