# Generated by Django 2.2.1 on 2019-06-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birth_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='expiration_year',
            field=models.CharField(max_length=20),
        ),
    ]
