# Generated by Django 2.2.1 on 2019-06-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubapp', '0002_auto_20190603_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birth_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='expiration_year',
            field=models.CharField(max_length=50),
        ),
    ]
