# Generated by Django 2.2.1 on 2019-06-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubapp', '0003_auto_20190603_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
